resources:
- deployment.yaml
- service.yaml

images:
- name: sidneckel/backend
  newName: sidneckel/backend
  newTag: be601fedf7df47ce4b166215a738a8d6cb103e06
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
