apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3333
      targetPort: 80
      nodePort: 30001
